"""empty message

Revision ID: 32485751c422
Revises: 
Create Date: 2019-03-30 16:55:38.050861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32485751c422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    op.drop_column('comments', 'body_html')
    # ### end Alembic commands ###
